services:
  php:
    build:
      context: .
      dockerfile: .docker/local/php/Dockerfile
    depends_on:
      - postgres
    environment:
      PHP_IDE_CONFIG: serverName=${PHP_IDE_CONFIG_SERVER_NAME}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: api.${PROJECT_NAME}.local
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/local/php
    volumes:
      - "./:/var/www/html"
      - "./.data/composer:/root/.composer"

  scheduler:
    build:
      context: .
      dockerfile: .docker/local/php/Dockerfile
    depends_on:
      - php
    environment:
      PHP_IDE_CONFIG: serverName=${PHP_IDE_CONFIG_SERVER_NAME}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/local/scheduler
    command: ["php", "artisan", "schedule:work"]
    volumes:
      - "./:/var/www/html"
      - "./.data/composer:/root/.composer"

#  queue:
#    build:
#      context: .
#      dockerfile: .docker/local/php/Dockerfile
#    depends_on:
#      - php
#    environment:
#      PHP_IDE_CONFIG: serverName=${PHP_IDE_CONFIG_SERVER_NAME}
#      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
#      POSTGRES_PORT: ${POSTGRES_PORT}
#      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
#      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/local/scheduler
#    command: ["php", "artisan", "queue:work"]
#    volumes:
#      - "./:/var/www/html"
#      - "./.data/composer:/root/.composer"

  nginx:
    build:
      context: .
      dockerfile: .docker/local/nginx/Dockerfile
    depends_on:
      - php
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/local/nginx
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./.docker/local/nginx/etc/default.conf:/etc/nginx/conf.d/default.conf"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: ${POSTGRES_HOSTNAME}
    ports:
      - "5432:5432"
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"

  node:
    build:
      context: .
      dockerfile: .docker/local/node/Dockerfile
    environment:
      VITE_PORT: ${VITE_PORT:-5173}
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/local/node
    command: ["npm", "run", "dev", "--host"]
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - "./:/app"
      - "./.data/node:/root/.npm"
